version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: &backend
      context: .
    entrypoint: /app/run_server.sh
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: *backend
    entrypoint: /app/run_worker.sh
    volumes:
      - static_volume:/app/static/
    env_file:
      - .env
    depends_on:
      - backend
      - redis

volumes:
  static_volume:
  media_volume:
  postgres_volume:
